### ISSUE TITLE
Error when run cellchat method with other database 

### ISSUE THREAD

**Issue by XUEbaogai0101** [SunXQlab/CCCbank#2]
![5cc74f074dc0910991af42b6350caaa](https://github.com/SunXQlab/CCCbank/assets/103372530/ac9c28d5-ceb4-44be-aae2-80cfc6c3c6c8)

**Comment by Luojiax** [comment]
The first error was caused by a spelling error in FANTOM5. It's FANTOM5, not FAMTOM5.
About the second error, could you provide the messages of traceback() and sessionInfo(), and send them to the email sunxq6@mail.sysu.edu.cn?

**Comment by XUEbaogai0101** [comment]
Thank you! I believe you may need to change the word 'FAMTOM5' to 'FANTOM5' in the tutorial. By the way, I used cellchat2 to run the function. There might be some compatibility issues.

**Comment by Luojiax** [comment]
Thanks for the reminder, the spelling error in tutorial has been corrected.
The functions of CellChat in CCCbank were built based on CellChat v1. And the number of columns in the prior databases of CellChat v1 and CellChat v2 is different, so errors may occur when running CCCbank with CellChat v2.
